---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install remi-release-7.rpm
  yum:
    name: "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"
    state: present

- name: install pygpgme
  yum:
    name: pygpgme
    state: present

- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: install system-dependencies
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gzip
      - lsof
      - nice
      - sed
      - tar

- name: install httpd
  yum:
    name: httpd
    state: present

- name: import Elasticsearch GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: deploy elasticsearch.repo.j2
  template:
    src: templates/elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: '644'

- name: install Elasticsearch
  yum:
    name: elasticsearch
    enablerepo: elasticsearch

- name: deploy varnishcache_varnish65.repo.j2
  template:
    src: templates/varnishcache_varnish65.repo.j2
    dest: /etc/yum.repos.d/varnishcache_varnish5.repo
    owner: root
    group: root
    mode: '644'
  notify:
    - import Varnish GPG key

- name: install Varnish
  yum:
    name: varnish

- name: systemctl start httpd
  service:
    name: httpd
    state: stareted
    enabled: yes

- name: install php, php-extensions
  yum:
    name: "{{ packages }}"
    state: present
    enablerepo: remi-php74
  vars:
    packages:
      - php
      - php-bcmath
      - php-ctype
      - php-curl
      - php-dom
      - php-gd
      - php-hash
      - php-iconv
      - php-intl
      - php-mbstring
      - php-mysql
      - php-opcache
      - php-openssl
      - php-pdo
      - php-simplexml
      - php-soap
      - php-sockets
      - php-xsl
      - php-xdebug
      - php-zip

- name: check composer
  stat:
    path: /usr/local/bin/composer
  register: composer
  changed_when: false

- name: download composer installer (first time only)
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  when: composer.stat.exists == false

- name: install composer (first time only)
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  when: composer.stat.exists == false

- name: rename composer.phar to composer (first time only)
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  when: composer.stat.exists == false

- name: make composer executable (first time only)
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file

- name: install mysql
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mysql80-community-release-el7-3.noarch.rpm
      - mysql-community-server

- name: systemctl start mysql
  service:
    name: mysqld
    state: stareted
    enabled: yes


