---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install remi-release-7.rpm
  yum:
    name: "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"
    state: present

- name: install system-dependencies
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gzip
      - lsof
      - sed
      - tar

- name: install pygpgme
  yum:
    name: pygpgme
    state: present

- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: install httpd
  yum:
    name: httpd
    state: present

- name: systemctl start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: deploy httpd.conf.j2
  template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '644'
    backup: yes
  notify:
    - restart httpd

- name: import Elasticsearch GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: deploy elasticsearch.repo.j2
  template:
    src: templates/elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: '644'

- name: install Elasticsearch
  yum:
    name: elasticsearch
    enablerepo: elasticsearch

- name: deploy varnishcache_varnish65.repo.j2
  template:
    src: templates/varnishcache_varnish65.repo.j2
    dest: /etc/yum.repos.d/varnishcache_varnish5.repo
    owner: root
    group: root
    mode: '644'
  register: varnishcache_varnish65_repo_deployment

- name: import Varnish GPG key
  command:
    cmd: yum -q makecache -y --disablerepo='*' --enablerepo='varnishcache_varnish65'
    warn: yes
  when: varnishcache_varnish65_repo_deployment.changed

- name: install Varnish
  yum:
    name: varnish

- name: install redis
  yum:
    name: redis
    state: present

- name: install php, php-extensions
  yum:
    name: "{{ packages }}"
    state: present
    enablerepo: remi-php74
  vars:
    packages:
      - php
      - php-bcmath
      - php-ctype
      - php-curl
      - php-dom
      - php-gd
      - php-hash
      - php-iconv
      - php-intl
      - php-mbstring
      - php-mysql
      - php-opcache
      - php-openssl
      - php-pdo
      - php-simplexml
      - php-soap
      - php-sockets
      - php-xsl
      - php-xdebug
      - php-zip

- name: deploy rabbitmq.repo.j2
  template:
    src: templates/rabbitmq.repo.j2
    dest: /etc/yum.repos.d/rabbitmq.repo
    owner: root
    group: root
    mode: '644'

- name: install RabbitMQ dependencies
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - socat
      - logrotate

- name: install Erlang and RabbitMQ
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - erlang
      - rabbitmq-server

- name: check composer
  stat:
    path: /usr/local/bin/composer
  register: composer
  changed_when: false

- name: download composer installer (first time only)
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  when: composer.stat.exists == false

- name: install composer (first time only)
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  when: composer.stat.exists == false

- name: rename composer.phar to composer (first time only)
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  when: composer.stat.exists == false

- name: make composer executable (first time only)
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file

- name: install mysql repository
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    state: present

- name: install mysql 
  yum:
    name: mysql-server
    state: present

- name: systemctl start mysql
  service:
    name: mysqld
    state: started
    enabled: yes

