---
- hosts: all
  become: yes
  tasks:
    - name: selinux desabled
      selinux:
        state: disabled

    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: start/enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: install epel-release
      yum:
        name: epel-release
        state: present

    - name: install remi-release-7.rpm
      yum:
        name: "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"

    - name: install php/library
      yum:
        name: ['php', 'php-mysql', 'php-common', 'php-mbstring', 'php-json', 'php-xml', 'php-zip', 'php-curl','php-intl', 'php-apcu', 'php-opcache']
        state: present
        enablerepo: remi,remi-php73

    - name: check mysql log file exists
      stat: 
        path: /var/log/mysqld.log
      register: log_file
      changed_when: false

    - name: install mysql5.7 
      yum:
        name: 'http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm'
        state: present

    - name: install mysql-server 
      yum:
        name: mysql-community-server
        state: present

    - name: install MySQL-python
      yum:
        name: MySQL-python
        state: present

    - name: deploy .my.cnf
      template:
        src: files/my.cnf
        dest: /root/.my.cnf
        owner: root
        group: root
                            
    - name: mysql start / enable
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: get temporary password
      shell: cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
      register: mysql_default_password
      when: log_file.stat.exists == false

    - name: change root user password for updating expiration date
      shell: mysql -u root -p'{{ mysql_default_password.stdout }}' --connect-expired-password -e "set password for root@'localhost'=password('Tmp_Passw0rd');"
      when: log_file.stat.exists == false

    - name: uninstall validate_password
      shell: |
        mysql -u root -p'Tmp_Passw0rd' --connect-expired-password -e "uninstall plugin validate_password;"
      when: log_file.stat.exists == false

    - name: change root user password
      shell: |
        mysql -u root -p'Tmp_Passw0rd' --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Larave1.pass';"
      when: log_file.stat.exists == false

    - name: create laradb
      mysql_db:
        name: laradb
        state: present

    - name: create mysql user
      mysql_user: 
        name: larauser 
        host: localhost 
        password: Larave1.pass 
        priv: 'laradb.*:ALL,GRANT' 
        state: present

    - name: create root@'%' user
      mysql_user: 
        name: root 
        host: '%' 
        password: Larave1.pass 
        priv: '*.*:ALL,GRANT' 
        state: present

    - name: check composer
      stat: 
        path: /usr/local/bin/composer
      register: composer
      changed_when: false

    - name: download composer installer (first time only)
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer
      when: composer.stat.exists == false

    - name: install composer (first time only)
      shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
      when: composer.stat.exists == false

    - name: rename composer.phar to composer (first time only)
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      when: composer.stat.exists == false

    - name: make composer executable (first time only)
      file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file

