version: 2.1
commands:
  sayhello:
    description: "Say Hello"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: Echo Hello << parameters.to >>

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - sayhello:
          to: Everyone
