import React from "react";
import {Layout} from "../layout";

const About = () => (
    <Layout>
        <h1 className='text-2xl'>Contact page</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, est illum in maxime minus necessitatibus, nulla numquam recusandae, soluta tempore velit vitae voluptates. Accusamus aperiam at, consequuntur debitis error excepturi iste labore necessitatibus nemo quaerat, quibusdam recusandae vel veniam. Assumenda eligendi itaque sequi voluptas voluptatem. A adipisci asperiores consectetur cum distinctio dolor doloribus dolorum eaque excepturi fugiat harum in iure labore laboriosam laborum magnam maxime minima molestiae, nemo nesciunt, nobis nostrum numquam obcaecati odit officia officiis omnis perferendis porro provident quae quibusdam quos reprehenderit sint sit sunt suscipit, velit. A adipisci beatae ea est eum, maxime molestias porro possimus sit!</p>
    </Layout>
);

export default About;
