---
- name: deploy nginx.repo.j2
  template:
    src: templates/nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: '644'

- name: install nginx
  yum:
    name: nginx

- name: deploy nginx.repo.j2
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '644'

- name: systemctl start nginx
  service:
    name: nginx
    state: started
    enabled: yes

