- name: install postgresql
  yum:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    state: present

- name: install postgresql13-server
  yum:
    name: postgresql13-server
    state: present
    
